export const ERROR_CODES = {
  // Project creation
  SUPABASE_SLOTS_FULL:
    "Your Supabase account already has projects. LaunchPad needs 2 free project slots (for staging and production). Please delete existing projects or upgrade your Supabase plan, then try again.",
  PROJECT_LIMIT_REACHED:
    "You already have a LaunchPad project. Free-tier users are limited to 1 project. Upgrade to LaunchPad Pro for multiple projects.",
  PROJECT_NAME_TAKEN: "A project with this name already exists.",

  VERCEL_GITHUB_NOT_CONNECTED:
    "Your Vercel account is not connected to GitHub. LaunchPad needs this to link your GitHub repos to Vercel for automatic deployments.",

  // Preview limits
  PREVIEW_LIMIT_REACHED:
    "You have 5 active preview environments, which is the maximum for your plan. Merge or delete a branch to free up a slot, or upgrade your Supabase plan for more.",

  // Guard failures
  MISSING_SCHEMA_PRISMA:
    "Your project is missing prisma/schema.prisma. This file is required for database management. If you removed it intentionally, you may need to re-scaffold with `launchpad init`.",
  CONFIG_MODIFIED:
    ".launchpad/config.json has been modified. This file is managed by LaunchPad and must not be edited. Run `launchpad validate --fix` to restore it, or re-scaffold with `launchpad init`.",
  CLAUDE_MD_MODIFIED:
    "The LaunchPad section of your CLAUDE.md has been modified. This may cause Claude Code to generate code that doesn't work with the deploy pipeline. Please restore the platform section above the --- delimiter.",
  DESTRUCTIVE_MIGRATION:
    "Your schema changes include destructive operations that would delete data. Please confirm this is intentional in the LaunchPad dashboard before deploying.",
  ENV_FILE_COMMITTED:
    "It looks like a .env file was committed to the repo. LaunchPad manages your environment variables automatically — this file is unnecessary and may contain secrets. Consider removing it.",
  MANUAL_MIGRATION_DETECTED:
    "A migration file was found in /prisma/migrations/ that wasn't generated by LaunchPad. LaunchPad manages migrations automatically — manually created files may cause conflicts.",

  // Deploy
  VERCEL_DEPLOY_LIMIT_WARNING:
    "You've used {count} of your 100 daily Vercel deploys. Consider batching changes into fewer pushes.",
  VERCEL_HOBBY_COMMERCIAL_WARNING:
    "Vercel's free plan is for personal, non-commercial use. If this project is commercial, please upgrade to Vercel Pro ($20/mo).",

  // Drift
  SCHEMA_DRIFT_DETECTED:
    "Your {environment} database has changes that aren't in your Prisma schema. This was probably added directly in the Supabase dashboard. To fix this, add the changes to prisma/schema.prisma and push.",
} as const;
